### ISSUE TITLE
Implement multi args constructors

### ISSUE THREAD

**Issue by piiertho** [utopia-rise/godot-jvm#69]
For now only JVM no args constructors can be called from cpp.  
We'd like to provide a way to call multi-args constructors.  
A first approach would be to allow one constructor per argument count.  
This means if you register this constructor for a class:  
```kotlin
constructor(i: Int, o: Object)
```
You would not be able to register another constructor with two arguments for this class (as c# implem IIRC).

This would need few modifications of engine code in `KotlinScript` and `KtClass`.  
This would need JVM glue code modification on `KtClass`.  
This would also need some registration and idea plugin modifications I think.

For performance purpose, we should use arrays to store constructors and indices should be argument count.

**Comment by chippmann** [comment]
Implemented with #80
